# 使用官方 Python 镜像
FROM python:3.12-slim

# 设置工作目录
WORKDIR /callback

# 复制依赖文件并安装
COPY ./callback/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 复制整个项目
COPY ./callback .

# 环境变量
ENV FLASK_APP=run.py
ENV PYTHONUNBUFFERED=1

EXPOSE 8669
# 使用 gunicorn 启动 Flask（加载 run.py 中的 app）
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8669", "run:app"]
